### ISSUE TITLE
10k queries in about 2 hours?

### ISSUE THREAD

**Issue by ZenMasta** [ram-on/SkyTube#579]
Due to API issues as noted on https://github.com/ram-on/SkyTube/issues/479  I have decided to use my own API credentials. This morning I was using using skytube while doing some work and after doing a query I got this message about the Daily Limit exceeded and how the quota would reset at midnight.

However, I only have I think less than 40 subs I'm not really certain because I don't know how to check. I just know that when I went through the process of importing from the youtube backup, I only chose my absolute favorites. I only refreshed the feed a couple of times, and did a few manual searches. 

V2.965 Extra (2019-09-27 13:44)

Is this normal, I feel like this is super abnormal to burn through 10k queries with such little activity.Seems to me the Queries per 100 seconds doesn't really match the Queries per day.
![Qper100s](https://user-images.githubusercontent.com/823528/66238964-86fd7900-e6ad-11e9-99ed-29a98f5e61b5.png)
![QperDay](https://user-images.githubusercontent.com/823528/66238967-895fd300-e6ad-11e9-860b-605435e070e4.png)

**Comment by ZenMasta** [comment]
So, it happened again today, except I literally only just opened skytube for the first time, cancelled the refresh fee and performed one search. Then the second search, incidentally the same channel prompted the error. But when I go to my quota, it's not showing any usage

**Comment by gzsombor** [comment]
It's really strange, indeed. I guess, the API calls are not aggregated in real time, so that's why you haven't seen any calls just after you've opened the app. Maybe latter?
Could you check the more detailed statistics about the individual calls?
 It should be somewhere there: https://console.developers.google.com/apis/api/youtube.googleapis.com/metrics?project=<your-project-id>

**Comment by ZenMasta** [comment]
For what it's worth, I have 56 channels I'm subbed to in the app. 
![youtube-quotas](https://user-images.githubusercontent.com/823528/66283500-94b32a00-e878-11e9-996a-44e48b06e4b3.png)
![api-traffic](https://user-images.githubusercontent.com/823528/66283795-c1b40c80-e879-11e9-8a48-797fffda3e1a.png)

**Comment by ZenMasta** [comment]
Still experiencing this with todays update. And I haven't been able to use the the app because feeds had kept crashing it from the update before that. And first time opening it, i hit my quota. Is there something up with my setup because I feel like if this was wide spread everyone would be in here posting. The app is virtually unusable except maybe MAYBE once a day. and well today, couldnt even use it

**Comment by Octav14n** [comment]
I too have problems with my quota and my own API key. I have no idea where I find the relevant data. Yesterday I could reaload my feed 4-5 times before the Toast-message appeared, today it appeared emidiatly.
In the Google-API-Console I could find the entry:
Method: youtube.search.list 	Queries: 1.361 	Error-Rate: 75,9 %
I have no idea if this is relevant.

**Comment by gzsombor** [comment]
How youtube counts the calls is a bit mistery for me - I guess, when the metadata of the individual videos are retrieved, then each ID counts as an extra, separate call, although the video id's are concatenated together, and sent together in one http request. 
 What about switching to the NewPipe backend? In my experience, it works better

**Comment by MavropaliasG** [comment]
I continuously get the 'daily limit exceeded' error, what must I do?

**Comment by gzsombor** [comment]
I've implemented some extra check to avoid asking the same informations from the server repeatedly, hopefully this will solve this issue, please check it v2.968

**Comment by MavropaliasG** [comment]
I use 2.968 on Huawei p9 the problem persists. 

https://ibb.co/42c4c1z
